# Generated by Django 3.1.7 on 2021-03-13 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact1',
        ),
    ]
