# Generated by Django 3.2 on 2021-04-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contactadd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactadd',
            old_name='addproperty',
            new_name='addproperty1',
        ),
    ]
