# Generated by Django 3.2 on 2021-04-14 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_rename_addproperty_contactadd_addproperty1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactadd',
            old_name='addproperty_id',
            new_name='addproperty1_id',
        ),
    ]
