# Generated by Django 3.2 on 2021-04-14 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial')], max_length=200)),
                ('property_ower', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField()),
                ('kitchen', models.PositiveIntegerField(default=1)),
                ('hall', models.PositiveIntegerField(default=1)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=1)),
                ('balcony', models.PositiveIntegerField(default=0)),
                ('garage', models.PositiveIntegerField(default=0)),
                ('sqft', models.PositiveIntegerField()),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=5)),
                ('user_id', models.IntegerField(blank=True, default=1)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
