# Generated by Django 3.2 on 2021-04-14 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addproperty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproperty',
            old_name='property_ower',
            new_name='property_owner',
        ),
    ]
