# Generated by Django 3.2 on 2021-04-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproperty', '0002_rename_property_ower_addproperty_property_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproperty',
            name='image',
            field=models.BinaryField(blank=True),
        ),
    ]
