# Generated by Django 3.2 on 2021-04-14 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addproperty', '0003_addproperty_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproperty',
            name='image',
        ),
    ]
